/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      fontFamily: {
        kneyan: ["Kenyan Coffee", "sans-serif"],
      },
      colors: {
        background: "var(--dml-color-background)",
        foreground: "var(--dml-color-foreground)",
        "foreground/80": "rgba(12,12,12,0.8)",
        primary: "var(--dml-color-primary)",
        "primary-light": "var(--dml-color-primary-light)",
        secondary: "var(--dml-color-secondary)",
        danger: "var(--dml-color-danger)",
        "danger-light": "var(--dml-color-danger-light)",
        "danger-deep": "var(--dml-color-danger-deep)",
        "danger-badge": "var(--dml-color-danger-badge)",
        "warning-bg": "var(--dml-color-warning)",
        grey: "var(--dml-color-grey)",
        "grey-medium": "var(--dml-color-grey-medium)",
        "grey-btn": "var(--dml-color-grey-btn)",
        "grey-low": "var(--dml-color-grey-low)",
        "tag-bg": "var(--dml-color-tag-bg)",
        "tag-bg-deep": "var(--dml-color-tag-bg-deep)",
        "natural-white": "var(--dml-color-natural-white)",
        green: "var(--dml-color-green)",
        "green-low": "var(--dml-color-green-low)",
        "danger-medium": "var(--dml-color-danger-medium)",
        "purple-extra-light": "var(--dml-color-purple-extra-light)",
        "purple-light": "var(--dml-color-purple-light)",
        "purple-medium": "var(--dml-color-purple-medium)",
        "purple-deep": "var(--dml-color-purple-deep)",
        "red-light": "var(--dml-color-red-light)",
        "red-medium": "var(--dml-color-red-medium)",
        "red-deep": "var(--dml-color-red-deep)",
        "yellow-light": "var(--dml-color-yellow-light)",
        "yellow-medium": "var(--dml-color-yellow-medium)",
        "yellow-deep": "var(--dml-color-yellow-deep)",
        "green-extra-light": "var(--dml-color-green-extra-light)",
        "green-badge": "var(--dml-color-green-badge)",
        "green-light": "var(--dml-color-green-light)",
        "green-medium": "var(--dml-color-green-medium)",
        "green-middle": "var(--dml-color-green-middle)",
        "green-deep": "var(--dml-color-green-deep)",
        "blue-light": "var(--dml-color-blue-light)",
        "blue-medium": "var(--dml-color-blue-medium)",
        "lily-white": "var(--dml-color-lily-white)",
        "titan-white": "var(--dml-color-titan-white)",
        "serenade-white": "var(--dml-color-serenade-white)",
        disabled: "var(--dml-color-disabled)",
      },
      boxShadow: {
        "dml-box-shadow": "var(--dml-box-shadow)",
        "custom-dml-1": "var(--dml-box-shadow)",
        "custom-2": "var(--dml-dropdown-shadow)",
      },
      spacing: {
        "5px": "5px",
        4.5: "18px",
      },
      padding: {
        17: "17px",
      },
      backgroundImage: {
        "login-bg": "url('/images/login-bg.png')",
      },
      screens: {
        "max-xs": "350px",
        sm: "576px",
        md: "768px",
        lg: "992px",
        xl: "1170px",
        "2xl": "1170px",
      },
      backgroundSize: {
        "home-bg": "33%",
      },
      container: {
        padding: {
          DEFAULT: "0",
          sm: "0",
          lg: "0",
          xl: "0",
          "2xl": "0",
        },
      },
      keyframes: {
        fadeInUp: {
          "0%": { opacity: 0, transform: "translateY(20px)" },
          "100%": { opacity: 1, transform: "translateY(0)" },
        },
      },
      animation: {
        fadeInUp: "fadeInUp 0.4s ease-out",
      },
    },
  },
  plugins: [],
};
