export const patients = [
  {
    clinicOrderId: "#3287",
    clinicName: "Empathy Medical Center",
    orderId: "#3287",
    rxNumber: "#3278",
    prescribeDate: "09-29-2024",
    patientName: "Darlene Robertson",
    doctorName: "Chris Rock",
    source: "MangoRx",
    medication: "Testosterone Cypionate",
    status: "Waiting",
    trackingNumber: "09TGJ5E289",
    note: "Need more reports from patient more reports from patient",
    action: "icon-Through",
  },
  {
    clinicOrderId: "#3287",
    clinicName: "Empathy Medical Center",
    orderId: "#3287",
    rxNumber: "#3278",
    prescribeDate: "09-29-2024",
    patientName: "Darlene Robertson",
    doctorName: "Chris Rock",
    source: "MangoRx",
    medication: "Testosterone Cypionate",
    status: "Received",
    trackingNumber: "09TGJ5E289",
    note: "Need more reports from patient more reports from patient",
    action: "icon-Through",
  },
  {
    clinicOrderId: "#3287",
    clinicName: "Empathy Medical Center",
    orderId: "#3287",
    rxNumber: "#3278",
    prescribeDate: "09-29-2024",
    patientName: "Darlene Robertson",
    doctorName: "Chris Rock",
    source: "MangoRx",
    medication: "Testosterone Cypionate",
    status: "Shipped",
    trackingNumber: "09TGJ5E289",
    note: "Need more reports from patient more reports from patient",
    action: "icon-Through",
  },
  {
    clinicOrderId: "#3287",
    clinicName: "Empathy Medical Center",
    orderId: "#3287",
    rxNumber: "#3278",
    prescribeDate: "09-29-2024",
    patientName: "Darlene Robertson",
    doctorName: "Chris Rock",
    source: "MangoRx",
    medication: "Testosterone Cypionate",
    status: "Canceled",
    trackingNumber: "09TGJ5E289",
    note: "Need more reports from patient more reports from patient",
    action: "icon-Through",
  },
  {
    clinicOrderId: "#3287",
    clinicName: "Empathy Medical Center",
    orderId: "#3287",
    rxNumber: "#3278",
    prescribeDate: "09-29-2024",
    patientName: "Darlene Robertson",
    doctorName: "Chris Rock",
    source: "MangoRx",
    medication: "Testosterone Cypionate",
    status: "Delivered",
    trackingNumber: "09TGJ5E289",
    note: "Need more reports from patient more reports from patient",
    action: "icon-Through",
  },
  {
    clinicOrderId: "#3287",
    clinicName: "Empathy Medical Center",
    orderId: "#3287",
    rxNumber: "#3278",
    prescribeDate: "09-29-2024",
    patientName: "Darlene Robertson",
    doctorName: "Chris Rock",
    source: "MangoRx",
    medication: "Testosterone Cypionate",
    status: "Hold",
    trackingNumber: "09TGJ5E289",
    note: "Need more reports from patient more reports from patient",
    action: "icon-Through",
  },
  {
    clinicOrderId: "#3287",
    clinicName: "Empathy Medical Center",
    orderId: "#3287",
    rxNumber: "#3278",
    prescribeDate: "09-29-2024",
    patientName: "Darlene Robertson",
    doctorName: "Chris Rock",
    source: "MangoRx",
    medication: "Testosterone Cypionate",
    status: "Waiting",
    trackingNumber: "09TGJ5E289",
    note: "Need more reports from patient more reports from patient",
    action: "icon-Through",
  },
  {
    clinicOrderId: "#3287",
    clinicName: "Empathy Medical Center",
    orderId: "#3287",
    rxNumber: "#3278",
    prescribeDate: "09-29-2024",
    patientName: "Darlene Robertson",
    doctorName: "Chris Rock",
    source: "MangoRx",
    medication: "Testosterone Cypionate",
    status: "Shipped",
    trackingNumber: "09TGJ5E289",
    note: "Need more reports from patient more reports from patient",
    action: "icon-Through",
  },
  {
    clinicOrderId: "#3287",
    clinicName: "Empathy Medical Center",
    orderId: "#3287",
    rxNumber: "#3278",
    prescribeDate: "09-29-2024",
    patientName: "Darlene Robertson",
    doctorName: "Chris Rock",
    source: "MangoRx",
    medication: "Testosterone Cypionate",
    status: "Delivered",
    trackingNumber: "09TGJ5E289",
    note: "Need more reports from patient more reports from patient",
    action: "icon-Through",
  },
  {
    clinicOrderId: "#3287",
    clinicName: "Empathy Medical Center",
    orderId: "#3287",
    rxNumber: "#3278",
    prescribeDate: "09-29-2024",
    patientName: "Darlene Robertson",
    doctorName: "Chris Rock",
    source: "MangoRx",
    medication: "Testosterone Cypionate",
    status: "Received",
    trackingNumber: "09TGJ5E289",
    note: "Need more reports from patient more reports from patient",
    action: "icon-Through",
  },
];
