export const questions = [
  { name: "primaryGoal", label: "What is your primary goal for weight loss?" },
  { name: "amountOfWeightLoss", label: "How much weight would you like to lose?" },
  { name: "hasAllergy", label: "Do you have any allergy?" },
  { name: "nameAllergy", label: "Please list any allergies you have (example: Sneezing, Runny Nose, Skin Rash, Difficulty Breathing and etc.):" },
  { name: "prescribed", label: "Do you take any prescribed medications?" },
  {
    name: "medicines",
    label:
      "Please specify what medications have you taken?  (Example: [medication name] - [dosage] - [duration], [medication name] - [dosage] - [duration]. If unknown, write 'unknown')",
  },
  { name: "exerciseTimes", label: "How often do you exercise?" },
  { name: "doesDiet", label: "Are you willing to follow a weight loss dietary plan/reduce calories and exercise?" },
  { name: "agreeGlpExercise", label: "I acknowledge that GLP medications are most effective when used in conjunction with exercise." },
  { name: "hadPrevWeightLoss", label: "Have you had any previous weight loss attempts or programs?" },
  { name: "descPrevWeightLoss", label: "Please select the statement that best describes your previous weight loss attempts." },
  { name: "anyEatingDisorder", label: "Have you been diagnosed with any eating disorders or have a history of disordered eating?" },
  { name: "currentDiagnose", label: "What are you diagnosed with?" },
  { name: "currentDiagOther", label: "What are you diagnosed with?" },
  { name: "pastDiagnose", label: "What were you diagnosed with?" },
  { name: "pastDiagBullmia", label: "How long has it been since you were diagnosed?" },
  { name: "pastDiagOther", label: "What were you diagnosed with?" },
  { name: "isPregnant", label: "Are you currently?" },
  { name: "takesDrug", label: "Do you use recreational drugs?" },
  { name: "whatDrugs", label: "What drugs do you use?" },
  { name: "whatDrugsOther", label: "What drugs do you use?" },
  { name: "amountOfAlcohol", label: "How much alcohol do you drink?" },
  { name: "medicalCondition", label: "Do you suffer from any of these medical conditions?" },
  { name: "cardioVascularDisease", label: "Select all the conditions that apply to you." },
  { name: "highCholesterol", label: "Do you have cholesterol greater than 240 or are you on a cholesterol medication?" },
  { name: "triglyceride", label: "Did you ever have a fasting triglyceride level above 500?" },
  { name: "hypertension", label: "Are you taking high blood pressure medication for Hypertension?" },
  { name: "warfarin", label: "Are you on Warfarin?" },
  { name: "thyroidism", label: "Do you have a history of any of the following?" },
  { name: "thyroidCancer", label: "Do you have a personal or family history of thyroid cancer?" },
  { name: "thyroidCancerType", label: "What type of thyroid cancer?" },
  { name: "papillaryReport", label: "Do you have accurate lab report?" },
  { name: "papillaryReportUp", label: "Please upload your pathology report." },
  { name: "follicularReport", label: "Do you have your pathology report?" },
  { name: "follicularReportUp", label: "Please upload your pathology report." },
  { name: "thyroidCancerOther", label: "What type of thyroid cancer?" },
  { name: "thyroidOtherReport", label: "Do you have your pathology report?" },
  { name: "thyroidOtherReportUp", label: "Please upload your pathology report." },
  { name: "gallbladder", label: "Do you have a personal history of gallbladder disease?" },
  { name: "removedGallbladder", label: "Did you have your gallbladder removed?" },
  { name: "whenGallbladderRemoved", label: "When did you have your gallbladder removed?" },
  { name: "pancreatitis", label: "Do you have a personal history of acute or chronic pancreatitis?" },
  { name: "gallstones", label: "Did you have your gallbladder removed due to pancreatitis from gallstones?" },
  { name: "removedGallbladderGallstones", label: "When did you have your gallbladder removed?" },
  { name: "endocrineNeoplasia", label: "Do you have a personal or family history of multiple endocrine neoplasia?" },

  { name: "diabeticStatus", label: "Are you pre-diabetic or diabetic?" },
  { name: "takeDiabeticDrugName", label: "Are you currently taking any of the following medications? Select all that apply. (Select Multiple)" },
  { name: "takeDiabeticHemoglobin", label: "What is your hemoglobin A1C?" },
  { name: "cpapWithDiagonSedSleep", label: "Are you on CPAP with diagnosed Sleep Apnea?" },
  { name: "haveBariantricSurgery", label: "Have you had bariatric surgery within the last 12 months?" },
  { name: "takenGlpMedication", label: "Have you taken a GLP-1 medication in the past 30 days?" },
  { name: "heightWhenStartGlp", label: "What was your height when you started the GLP-1 medication?" },
  { name: "weightWhenStartGlp", label: "What was your weight when you started the GLP-1 medication" },
  { name: "currentWeightLossMedication", label: "Which weight loss medication are you currently taking?" },
  { name: "sema_lastWeightLossMedicationDoase", label: "What was the last dosage you took?" },
  { name: "sema_lastWeightLossMedicationDoaseOther", label: "What was the last dosage you took?" },
  { name: "sema_hasPdfForPreviousRx", label: "Do you have a PDF of your previous script, or a picture of your current vial?" },
  { name: "sema_previousRxDocument", label: "Please upload your script or a picture of your current vial." },
  { name: "tirz_lastWeightLossMedicationDoase", label: "What was the last dosage you took?" },
  { name: "tirz_lastWeightLossMedicationDoaseOther", label: "What was the last dosage you took?" },
  { name: "tirz_hasPdfForPreviousRx", label: "Do you have a PDF of your previous script, or a picture of your current vial?" },
  { name: "tirz_previousRxDocument", label: "Please upload your script or a picture of your current vial." },
  { name: "howLongTakeGlpMedication", label: "How long have you been taking the medication consecutively?" },
  { name: "howLongTakeGlpCurrentDosage", label: "How long have you been on your current dose?" },
  { name: "wouldYouLikeContinueGlpCurrentDosage", label: "Would you like to continue your current dose, move up to the next dose, or titrate down?" },
  { name: "stayCurrent_howLongTakeGlpCurrentDosage", label: "How long would you like to stay on your current dose?" },
  { name: "moveUp_wouldLikeToMoveUp", label: "How would you like to move up your dose?" },
  { name: "haveTakenMedicationAsPrescribed", label: "Have you been taking the medication as prescribed?" },
  { name: "No_haveDeviated", label: "Please explain how you have deviated from the dosing instructions" },
  { name: "glpSideEffect", label: "Have you experienced any of the following side effects?" },
  { name: "glpDrugEffectManageWeight", label: "How effective do you feel the medication has been in managing your weight?" },
  { name: "glpHowLongTaken", label: "How long has it been since you stopped taking your GLP medication?" },
  { name: "glpStartingHeight", label: "What was your height when you started the GLP-1 medication?" },
  { name: "glpStartingWeight", label: "What was your weight when you started the GLP-1 medication?" },
  { name: "takenPrevGlpMedication", label: "What GLP medication have you previously taken?" },
  { name: "takenPrevSema_lastDosage", label: "What was the last dosage you took?" },
  { name: "takenPrevSema_lastDosageOther", label: "What was the last dosage you took?" },
  { name: "takenPrevSema_hasPdfForPreviousRx", label: "Do you have a PDF of your previous script, or a picture of your current vial?" },
  { name: "takenPrevSema_previousRxDocument", label: "Please upload your script or a picture of your current vial." },
  { name: "takenPrevTirz_lastWeightLossMedicationDoase", label: "What was the last dosage you took?" },
  { name: "takenPrevTirz_lastWeightLossMedicationDoaseOther", label: "What was the last dosage you took?" },
  { name: "takenPrevTirz_hasPdfForPreviousRx", label: "Do you have a PDF of your previous script, or a picture of your current vial?" },
  { name: "takenPrevTirz_previousRxDocument", label: "Please upload your script or a picture of your current vial." },
  { name: "takenPrevGlp_sideEffect", label: "Did you experience any of the following side effects?" },
  { name: "takenPrevGlp_howEffective", label: "How effective do you feel the medication has been in managing your weight?" },

  { name: "peptidePrimaryGoal", label: "What is your primary goal with peptide therapy? (e.g. sleep, recovery, skin, energy, muscle)" },
  { name: "peptideTherapyUsed", label: "Have you used peptide therapies before?" },
  { name: "hormoneSensitiveCancers", label: "Do you have any history of hormone-sensitive cancers (e.g. breast, prostate)?" },
  { name: "endocrineAutoimmune", label: "Do you have any known endocrine or autoimmune disorders?" },
  { name: "hormoneTherapySupple", label: "Are you currently taking hormone therapy, supplements, or other performance enhancers?" },
  { name: "physicActLevel", label: "What is your typical physical activity level?" },
  { name: "peptideHealthHistory", label: "Health History (Needed for Peptide Treatments) (Please select all that apply):" },

  { name: "whenNotice", label: "When did you first notice hair loss or thinning?" },
  { name: "hairLossType", label: "Is your hair loss:" },
  { name: "hairLossArea", label: "Where is the hair loss most noticeable?" },
  { name: "familyHistory", label: "Do you have a family history of hair loss?" },
  { name: "recentStress", label: "Have you had recent stress, illness, or surgery?" },
  { name: "chronicCondition", label: "Do you have any chronic medical conditions?" },
  { name: "takingMeds", label: "Are you currently taking any medications or supplements?" },
  { name: "medsDetails", label: "Please specify the medications or supplements you are taking:" },
  { name: "excessiveShedding", label: "Do you notice excessive hair shedding while combing/washing?" },
  { name: "previousTreatments", label: "Have you tried hair loss treatments before?" },
  { name: "otherSymptoms", label: "Are you experiencing other symptoms?" },

  { name: "edDuration", label: "How long have you been experiencing erectile difficulties?" },
  { name: "erectionFrequency", label: "How often are you able to achieve and maintain an erection?" },
  { name: "morningErections", label: "Do you wake up with morning or nighttime erections?" },
  { name: "diagnosedCondition", label: "Do you have any diagnosed health conditions?" },
  { name: "takingMedications", label: "Are you currently taking any medications?" },
  { name: "medicationsList", label: "Do you take any prescribed medications?" },
  { name: "useSubstances", label: "Do you smoke, drink alcohol, or use recreational drugs?" },
  { name: "libido", label: "How is your sexual desire (libido)?" },
  { name: "priorEdTreatment", label: "Have you ever tried ED medications or treatments before?" },
  { name: "psychStress", label: "Are you experiencing psychological stress, anxiety, or depression?" },
  { name: "pelvicHistory", label: "Do you have any history of surgeries or injuries affecting the pelvic area?" },
  {
    name: "agreeToPhoneConsult",
    label:
      "Depending on state regulations, your provider may reach out to you to perform a consultation over the phone. Otherwise, your provider will review your intake forms and approve your script if all criteria are met",
  },
];
